from locust.core import HttpLocust, TaskSet, task
import hashlib
import random


class UserBehavior(TaskSet):
    """
    Class for load testing a JupyterHub environment

    First make sure that the JupyterHub authenticator is configured to
    accept any username or password combination.

    Then make sure the nb_file variable below is set to the URL Encoded
    name of the ipynb file that you wish to use with the text.

    To run the load test, cd to the directory with your locustfile.py
    and enter the following into the command line:
        locust --host=https://notebook.genepattern.org

    Then visit the load testing portal:
        http://localhost:8089
    """

    username = None
    password = None
    nb_file = 'GenePattern%20Python%20Tutorial.ipynb'

    @staticmethod
    def _random_token():
        """
        Generate a random username or password
        :return:
        """
        return hashlib.md5(str(random.random()).encode('utf-8')).hexdigest()

    def on_start(self):
        """
        Each user generated by the load tester should first authenticate
        :return:
        """
        self.username = self._random_token()
        self.password = self._random_token()

        self.client.post("/hub/login?next=", {
            "username": self.username,
            "password": self.password})

    @task
    def open_tree(self):
        self.client.get('/user/' + self.username + '/tree')

    @task
    def open_notebook(self):
        self.client.get('/user/' + self.username + '/notebooks/' + self.nb_file)


class WebsiteUser(HttpLocust):
    task_set = UserBehavior
    host = 'https://notebook.genepattern.org'
    min_wait = 9000
    max_wait = 12000
