# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-16 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=128)),
                ('quality', models.CharField(max_length=32)),
                ('publication', models.DateField()),
                ('owner', models.CharField(max_length=128)),
                ('file_path', models.CharField(max_length=256)),
                ('api_path', models.CharField(max_length=256)),
            ],
        ),
    ]
